# ==================================================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ==================================================================================================

server:
  port: ${SERVICE_PORT:9090}
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS



eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_SERVER_IP:localhost}:${REGISTRY_SERVER_PORT:8761}/eureka/
  instance:
    hostname: zuul-gateway-service
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
    
zuul:  routes:
    security-service:
      id: security-service
      service-id: security-service
      path: /api/security-service/**
      strip-prefix: true
    
    label-service:
      id: lael-service
      service-id: label-service
      path: /api/label-service/**
      strip-prefix: true
logging.file.name: ../logs/zuul-api-gateway-service.log