INSERT INTO public.available_language (id, created, deleted, guid, last_update, "version", code, dir, is_default, "label") VALUES(0, now(), false, uuid_generate_v4()::text, now(), 0,'en_US', 'ltr', true, 'English');

INSERT INTO public.available_language (id, created, deleted, guid, last_update, "version", code, dir, is_default, "label") VALUES(1, now(), false, uuid_generate_v4()::text, now(), 0,'ar_AR', 'rtl', true, 'العربية');

INSERT INTO public.available_language_messages (available_language_id, "key", value) VALUES (0, 'admin.security.roles.button.add.label', 'CREATE ROLE'), (0, 'admin.security.roles.button.refresh.label', 'RELOAD'),
	 (0, 'admin.security.roles.button.delete.label', 'DELETE'), (0, 'core.paginator.of.label', 'of'), (0, 'core.paginator.items.perpage.label', 'Items per page'), (0, 'core.paginator.first.page.label', 'First page'),
	 (0, 'core.paginator.last.page.label', 'Last page'), (0, 'core.paginator.next.page.label', 'Next page'), (0, 'core.paginator.previous.page.label', 'Previous page'), (0, 'core.listview.norecords.label', 'No Records Found!'),
	 (0, 'login.username.placeholder','Enter user name'), (0, 'login.username.required','User name is required'), (0, 'login.password.label','Password :'), (0, 'login.password.placeholder','Enter password'),
	 (0, 'login.password.required','Password is required'), (0, 'login.username.label','Username or email address'), (0, 'login.button.next.label','Sign in'), (0, 'login.title','Sign in to Portal'), (0, 'login.button.forgotpassword.label','Recover Password'),
	 (0, 'login.button.registration.label','No account? <a routerLink="/auth/register"> Sign up now</a>'), (0, 'forgotpassword.title','Reset your password'), (0, 'forgotpassword.button.next.label','Send password reset email'),
	 (0, 'forgotpassword.username.label','Email here...'), (0, 'forgotpassword.username.placeholder','Email here...'), (0, 'forgotpassword.username.required','That address is not a verified primary email'), (0, 'forgotpassword.button.login.label','Sign in existing account'),
	 (0, 'menu.dashboard','Dashboard'), (0, 'menu.country','Country'), (0, 'menu.persons','Persons'), (0, 'menu.persons.people','People');
INSERT INTO public.available_language_messages (available_language_id, "key", value) VALUES (0, 'menu.persons.languages','Languages'), (0, 'menu.admin','Configuration'), (0, 'menu.admin.security','Security'), (0, 'menu.admin.security.roles','Roles'),
	 (0, 'menu.admin.security.users','Users'), (0, 'menu.admin.labels','Property Bundles'), (0, 'admin.security.users.title','Users'), (0, 'admin.security.users.subtitle','An easy to use UI to help administrators manage user identities including password resets, creating and provisioning, blocking and deleting users.'),
	 (0, 'admin.security.roles.title','Roles'), (0, 'admin.security.roles.listview.columns.system.label','System'), (0, 'admin.security.roles.listview.columns.description.label','Description'), (0, 'admin.security.roles.listview.columns.name.label','Name'),
	 (0, 'admin.security.roles.listview.columns.created.label','Created On'), (0, 'admin.security.roles.listview.columns.id.label','#'), (0, 'admin.security.roles.subtitle','Create and manage Roles for your applications. Roles contain collections of Permissions and can be assigned to Users.'),
	 (0, 'pages.languages.browse.title','Languages'), (0, 'pages.languages.browse.subtitle',' '), (0, 'pages.languages.browse.helptext',' '), (0, 'pages.people.browse.title','People'), (0, 'pages.people.browse.subtitle',' '), (0, 'pages.people.browse.helptext',' '),
	 (0, 'pages.country.browse.title','Country'), (0, 'pages.country.browse.subtitle',' '), (0, 'pages.country.browse.helptext',' ');
	
INSERT INTO public.available_language_messages (available_language_id, "key", value) VALUES (1, 'core.paginator.of.label','من'), (1, 'core.paginator.items.perpage.label','مواد لكل صفحة'), (1, 'core.paginator.first.page.label','الصفحة الأولى'), (1, 'core.paginator.last.page.label','آخر صفحة'),
	 (1, 'core.paginator.next.page.label','الصفحة التالية'), (1, 'core.paginator.previous.page.label','الصفحة السابقة'), (1, 'core.listview.norecords.label','لا توجد سجلات!'), (1, 'login.title','تسجيل الدخول'), (1, 'login.username.label',':اسم المستخدم'), (1, 'login.username.placeholder','ادخل اسم المستخدم'),
	 (1, 'login.username.required','اسم المستخدم مطلوب'), (1, 'login.password.label',':كلمه السر'), (1, 'login.password.placeholder','أدخل كلمة المرور'), (1, 'login.password.required','كلمة المرور مطلوبة'), (1, 'login.button.next.label','تسجيل الدخول'), (1, 'login.button.registration.label','تسجيل'),
     (1, 'menu.dashboard','لوحة القيادة'), (1, 'menu.country','بلد'), (1, 'menu.persons','الأشخاص'), (1, 'menu.persons.people','اشخاص'), (1, 'menu.persons.languages','اللغات'), (1, 'menu.admin','ترتيب');
INSERT INTO public.available_language_messages (available_language_id, "key", value) VALUES (1, 'menu.admin.security','الأمان'), (1, 'menu.admin.security.roles','الأدوار'), (1, 'menu.admin.security.users','المستخدمون'), (1, 'menu.admin.labels','حزم العقارات'), (1, 'admin.security.users.title','المستخدمون'),
	 (1, 'admin.security.users.subtitle',' '), (1, 'admin.security.roles.title','الأدوار"'), (1, 'admin.security.roles.subtitle',' '), (1, 'admin.security.roles.listview.columns.id.label','#'), (1, 'admin.security.roles.listview.columns.created.label','تم إنشاؤها على'),
	 (1, 'admin.security.roles.listview.columns.name.label','اسم'), (1, 'admin.security.roles.listview.columns.description.label','وصف'), (1, 'admin.security.roles.listview.columns.system.label','هو نظام'), (1, 'pages.languages.browse.title',' اللغات'), (1, 'pages.languages.browse.subtitle',' '),
	 (1, 'pages.languages.browse.helptext',' '), (1, 'pages.people.browse.title',' اشخاص'), (1, 'pages.people.browse.subtitle',' '), (1, 'pages.people.browse.helptext',' '), (1, 'pages.country.browse.title',' بلد'), (1, 'pages.country.browse.subtitle',' '), (1, 'pages.country.browse.helptext',' ');