# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: DEBUG

spring:
  profiles:
    active: dev
    include:
      - swagger
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  jackson:
    serialization:
      indent-output: true
  mail:
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
    host: smtp.mailtrap.io
    username: 29bd8f8d5c3dd3
    password: 416d952c32e9e1
    port: 587
  boot:
    admin:
      notify:
        mail:
          enabled: false
    
# ================================================================================================================================================================================================
# Actuator configuration (management.*)
#
# Full list of properties with default values at:
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-actuator
# ================================================================================================================================================================================================

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

# ===================================================================
# Eureka server configuration (eureka.server.*)
#
# Full list of properties with default values at:
# https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaServerConfigBean.java
#
# Documentation at:
# https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/EurekaServerConfig.java
# ===================================================================

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${REGISTRY_SERVER_IP:localhost}:${REGISTRY_SERVER_PORT:8761}/eureka/
